name: RailKorea
version: ${project.version}
main: gold24park.railkorea.Main
depend: [ProtocolLib]
api-version: 1.19
commands:
  _reset_coin:
    description: 코인 발행 정보를 리셋합니다.
  trigger_event:
    description: 랜덤한 코인 이벤트가 발생됩니다.
  ban_coin:
    description: 설정한 코인들이 금지됩니다. 아무것도 적지않으면 모든 코인들이 활성화됩니다.
  coin_info:
    description: /coin_info 코인 발행정보를 한 눈에 살펴봅니다.
  issue_coin:
    description: /issue_coin [coin_name] [amount] 코인 발행량을 조절합니다.
  coin:
    description: /coin [player] [coin_name] [amount] 플레이어에게 특정코인을 지정한 만큼 줍니다.
  create_merchant:
    description: /create_merchant [player] [coin] 플레이어의 앞에 매입인을 스폰합니다.
  register:
    description: /register [player] [tag] [level] 플레이어에게 태그를 달아줍니다.
  home:
    description: /home 내 스폰 지점 좌표를 알려줍니다.
permissions:
  admin:
    description: 킹갓 관리자
    default: op